version: '0.0.1'
services:
  api:
    container_name: api
    build: 
      context: .
      dockerfile: ./build/Dockerfile
    volumes:
      - ./iris-app:/go/src/iris-app
    tty: true
    env_file:
      - ./build/.go_env
    environment:
      - TZ=Asia/Tokyo